### ISSUE TITLE
Lesson on learn.co is not showing, but all links work :)

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-resource-and-scaffold-generator#2]
Lesson can be read on GitHub, but the Learn.co page looks like this:

<img width="1226" alt="screen shot 2016-01-13 at 1 03 46 am" src="https://cloud.githubusercontent.com/assets/14326883/12280891/d03a5784-b991-11e5-88a2-288e414a3682.png">

 link to lesson: https://learn.co/tracks/full-stack-web-development/rails/crud-with-rails/resource-generator-routes

Forking, etc. works :)

**Comment by AnnJohn** [comment]
thanks for raising this issue. Not sure what the problem could be but have passed it along to our product team and this should be resolved by tomorrow morning. thanks again!

**Comment by AnnJohn** [comment]
this is fixed. thanks again!
