### ISSUE TITLE
Error in migration file

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/rails-resource-and-scaffold-generator#8]
The create_articles.rb migration file has a spelling error which causes an error when running the migration.

class CreateArticles < ActiveRecord::Migration
  def change
    create_table :articles do |t|
      t.tring :title     <<<<<< "tring" needs to be "string"
      t.text :body

      t.timestamps null: false
    end
  end
end

**Comment by cjbrock** [comment]
Hey @alexcrisan! I'm not sure what exactly you mean here. The migration files are automatically generated by the scaffold command, so unless you go in and edit them manually, it's highly unlikely for them to have a typo. Is it possible that you meant to put in an issue on a different lab?

Thanks!
// Corinna
